// SPDX-License-Identifier: AGPL-3.0-only
import assert from 'node:assert/strict';
import test from 'node:test';
import {readSpecificationDocuments, validateSpecification} from '../scripts/validate-specification.js';

// Independently authored minimal registry fixture, not generated by the validator.
function registryFixture() {
  return {
    sources: {schemaVersion: 1, registryVersion: '2026-09-08', sources: [
      {id: 'source.example', title: 'Example', url: 'https://example.org/spec', authority: 'Fixture', checkedAt: '2026-09-08'},
    ]},
    profiles: {schemaVersion: 1, registryVersion: '2026-09-08', defaultProfile: 'workshop-item', profiles: [
      {id: 'workshop-item', description: 'Fixture profile'},
    ]},
    constructs: {schemaVersion: 1, registryVersion: '2026-09-08', constructs: [
      {id: 'steam.bbcode.b', syntaxKind: 'pairedTag', tagName: 'b', contentModel: 'phrasing',
        provenance: [{sourceId: 'source.example', status: 'documented'}], profiles: {'workshop-item': 'documented'},
        gfmMapping: {fidelity: 'exact', strategy: 'mdast-strong'}, examples: ['[b]A[/b]']},
    ]},
  };
}

test('native schemas validate the maintained registry without claiming converter coverage', async () => {
  assert.doesNotThrow(() => validateSpecification(registryFixture()));
  validateSpecification(await readSpecificationDocuments());
});

test('native schemas reject invalid dates, syntax classifications and missing provenance', () => {
  const date = registryFixture();
  assert.ok(date.sources.sources[0]);
  date.sources.sources[0].checkedAt = '2026-02-30';
  assert.throws(() => validateSpecification(date), /format "date"/);
  const syntax = registryFixture();
  assert.ok(syntax.constructs.constructs[0]);
  syntax.constructs.constructs[0].syntaxKind = 'rendererTransformation';
  assert.throws(() => validateSpecification(syntax), /rendererKind|must NOT/);
  const provenance = registryFixture();
  assert.ok(provenance.constructs.constructs[0]);
  provenance.constructs.constructs[0].provenance = [];
  assert.throws(() => validateSpecification(provenance), /fewer than 1/);
});

test('source identities are unique even when their descriptions differ', () => {
  const documents = registryFixture();
  const source = documents.sources.sources[0];
  assert.ok(source);
  documents.sources.sources.push({...source, title: 'A conflicting source with the same identity'});
  assert.throws(() => validateSpecification(documents), /Duplicate source identity: source.example/);
});

test('provenance and profile references must resolve within the same registry version', () => {
  const source = registryFixture();
  assert.ok(source.constructs.constructs[0]?.provenance[0]);
  source.constructs.constructs[0].provenance[0].sourceId = 'source.missing';
  assert.throws(() => validateSpecification(source), /Unknown source: source.missing/);
  const profile = registryFixture();
  profile.profiles.defaultProfile = 'missing-profile';
  assert.throws(() => validateSpecification(profile), /Unknown default profile: missing-profile/);
  const version = registryFixture();
  version.constructs.registryVersion = '2026-09-09';
  assert.throws(() => validateSpecification(version), /Registry versions differ/);
});

test('a context-only renderer requires a reason and cannot claim a source syntax example', () => {
  const documents = registryFixture();
  const context = {id: 'steam.renderer.context', syntaxKind: 'rendererTransformation', rendererKind: 'context',
    contentModel: 'opaqueText', provenance: [{sourceId: 'source.example', status: 'communityObserved'}], profiles: {},
    gfmMapping: {fidelity: 'unsupported', strategy: 'preserve-source'}, observation: 'contextOnly',
    contextReason: 'The remote state is not supplied.', examples: []};
  const valid = {...documents, constructs: {...documents.constructs, constructs: [context]}};
  assert.doesNotThrow(() => validateSpecification(valid));
  assert.throws(() => validateSpecification({...valid, constructs: {...valid.constructs, constructs: [{...context, examples: ['invented syntax']}]}}), /examples|items/);
  assert.throws(() => validateSpecification({...valid, constructs: {...valid.constructs, constructs: [{...context, contextReason: ''}]}}), /contextReason/);
});
